service: user-management # Nombre de tu servicio

provider:
  name: aws
  runtime: nodejs18.x # Versión de Node.js que estás utilizando
  region: us-east-1 # Región en la que deseas desplegar
  environment:
    DB_HOST: your-db-host
    DB_USER: your-db-username
    DB_PASSWORD: your-db-password
    DB_NAME: your-db-name

functions:
  createUser:
    handler: src/controllers/userController.createUser # Ruta al manejador de la función
    events:
      - http:
          path: users
          method: post
          cors: true # Habilitar CORS si es necesario

  getUser:
    handler: src/controllers/userController.getUserById # Asegúrate de definir este método en tu controlador
    events:
      - http:
          path: users/{id}
          method: get
          cors: true

  updateUser:
    handler: src/controllers/userController.updateUser # Asegúrate de definir este método en tu controlador
    events:
      - http:
          path: users/{id}
          method: put
          cors: true

  deleteUser:
    handler: src/controllers/userController.deleteUser # Asegúrate de definir este método en tu controlador
    events:
      - http:
          path: users/{id}
          method: delete
          cors: true

package:
  individually: true # Empaqueta cada función de manera individual para optimizar el tamaño

